# @package _group_
path_dataset: data/raw/heart_disease_uci.csv
path_to_models: models/
path_to_report: models/report/
splitting_params:
  test_size: 0.2
  random_state: 8
feature_params:
  target_name: target
encoder_params:
  encoder_type: categorical
classifier_params:
  classifier_type: lgbm
  random_state: 8
  n_jobs: 2
  n_estimators: 10
  max_depth: 5
  num_leaves: 15